import matplotlib.pyplot as plt
def plotting(volDef, acDef, reDef, volAtt, acAtt, reAtt):
    f = plt.figure()
    f.set_figheight(2)
    f.set_figwidth(20)
    f.add_subplot(1,6,1)
    plt.plot(volDef)
    f.add_subplot(1,6,2)
    plt.plot(acDef)
    f.add_subplot(1,6,3)
    plt.plot(reDef)
    f.add_subplot(1,6,4)
    plt.plot(volAtt)
    f.add_subplot(1,6,5)
    plt.plot(acAtt)
    f.add_subplot(1,6,6)
    plt.plot(reAtt)
    plt.show(block=True)