is_disable_log: False
is_disable_y: False
vectorized_mode: False

env_config:
  clip_actions: True,
  sims_per_step: 20

simulation_config:
  # network_model_directory: '/home/toanngo/Documents/GitHub/cigar-document/ceds-cigar/pycigar/zzz/data/ieee3.dss'
  network_model_directory: '/home/michael/Desktop/git/ceds-cigar/pycigar/zzz/IEEE_13_Node/ieee13.dss'
  custom_configs:  {solution_mode: 1,
                    solution_number: 1,
                    solution_step_size: 1,
                    solution_control_mode: -1,
                    solution_max_control_iterations: 1000000,
                    solution_max_iterations: 30000,
                    power_factor: 0.9}

scenario_config:
  # network_data_directory: '/home/toanngo/Documents/GitHub/cigar-document/ceds-cigar/pycigar/zzz/data/load_solar_data.csv'
  network_data_directory: '/home/michael/Desktop/git/ceds-cigar/pycigar/zzz/IEEE_13_Node/load_solar_data.csv'
  multi_config: False
  start_end_time: [0, 14400]
  custom_configs: {load_scaling_factor: 1.00,
                   solar_scaling_factor: 1.50,
                   slack_bus_voltage: 1.04,
                   load_generation_noise: False,
                   power_factor: 0.9}

  nodes:
    - name: '671'
      devices:
          - name: pv_671
            device: pv_device
            custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                    gain: 1e5,
                                    low_pass_filter_measure_mean: 1.2,
                                    low_pass_filter_output_mean: 0.115}
            controller: fixed_controller
            custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
            # adversary_controller: fixed_controller
            # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
            # hack: [300, 0.4]

    - name: '634a'
      devices:
        - name: pv_634a
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '634b'
      devices:
        - name: pv_634b
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '634c'
      devices:
        - name: pv_634c
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '645'
      devices:
        - name: pv_645
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '646'
      devices:
        - name: pv_646
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '692'
      devices:
        - name: pv_692
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '675a'
      devices:
        - name: pv_675a
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '675b'
      devices:
        - name: pv_675b
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '675c'
      devices:
        - name: pv_675c
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '611'
      devices:
        - name: pv_611
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '652'
      devices:
        - name: pv_652
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '670a'
      devices:
        - name: pv_670a
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '670b'
      devices:
        - name: pv_670b
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    - name: '670c'
      devices:
        - name: pv_670c
          device: pv_device
          custom_device_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06],
                                  gain: 1e5,
                                  low_pass_filter_measure_mean: 1.2,
                                  low_pass_filter_output_mean: 0.115}
          controller: fixed_controller
          custom_controller_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.06]}
          # adversary_controller: fixed_controller
          # adversary_custom_controller_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
          # hack: [300, 0.4]

    # - name: bsd_671a
    #   devices:
    #       - name: bsd_671a
    #         device: battery_storage_device_advanced
    #         custom_device_configs: {
    #           default_control_setting: 'standby',
    #           total_capacity: 100,
    #           current_capacity: 90.0,
    #           max_charge_power: 100.00,
    #           max_discharge_power: 150.00,
    #           max_ramp_rate: 0.5,
    #           max_SOC: 1.0,
    #           min_SOC: 0.2
    #         }

    # - name: bsd_671b
    #   devices:
    #       - name: bsd_671b
    #         device: battery_storage_device_advanced
    #         custom_device_configs: {
    #           default_control_setting: 'standby',
    #           total_capacity: 100,
    #           current_capacity: 90.0,
    #           max_charge_power: 100.00,
    #           max_discharge_power: 150.00,
    #           max_ramp_rate: 0.5,
    #           max_SOC: 1.0,
    #           min_SOC: 0.2
    #         }

    # - name: bsd_671c
    #   devices:
    #       - name: bsd_671c
    #         device: battery_storage_device_advanced
    #         custom_device_configs: {
    #           default_control_setting: 'standby',
    #           total_capacity: 100,
    #           current_capacity: 90.0,
    #           max_charge_power: 100.00,
    #           max_discharge_power: 150.00,
    #           max_ramp_rate: 0.5,
    #           max_SOC: 1.0,
    #           min_SOC: 0.2
    #         }

  # controllers:
  #   - name: psc_bsd_671a
  #     controller: battery_peak_shaving_controller_dist
  #     custom_controller_configs: {
  #       default_control_setting: 'standby',
  #       lowpass_filter_frequency: 0.05, 
  #       active_power_target: 750,
  #       eta: 0.01,
  #       K_P: 0.75,
  #       K_I: 0.05,
  #       K_D: 0.02
  #     }
  #     list_devices: ['bsd_671a']

  #   - name: psc_bsd_671b
  #     controller: battery_peak_shaving_controller_dist
  #     custom_controller_configs: {
  #       default_control_setting: 'standby',
  #       lowpass_filter_frequency: 0.05, 
  #       active_power_target: 750,
  #       eta: 0.01,
  #       K_P: 0.75,
  #       K_I: 0.05,
  #       K_D: 0.02
  #     }
  #     list_devices: ['bsd_671b']

  #   - name: psc_bsd_671c
  #     controller: battery_peak_shaving_controller_dist
  #     custom_controller_configs: {
  #       default_control_setting: 'standby',
  #       lowpass_filter_frequency: 0.05, 
  #       active_power_target: 750,
  #       eta: 0.01,
  #       K_P: 0.75,
  #       K_I: 0.05,
  #       K_D: 0.02
  #     }
  #     list_devices: ['bsd_671c']
