language: python

cache: pip

python:
  - "3.6.8"

os: linux

dist: xenial

services:
  - xvfb

sudo: required

git:
  depth: 1

before_install:
  # install and run pep8 and docstyle tests
  - pip install pydocstyle
  #- pydocstyle --convention numpy --match-dir='[^\.].*'
  - pip install flake8
  - flake8 --version
  #- flake8 --show-source

  # Setup conda (needed for opencv, ray dependency)
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export TEST_FLAG="True"
  - conda config --append channels https://repo.anaconda.com/pkgs/free
  - conda config --append channels https://repo.anaconda.com/pkgs/pro

  # Requirements for stable baselines
  - sudo apt-get update && sudo apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev

  # Set up requirements for power
  - conda env create -f environment.yml
  - source activate pycigar

  - ls ../

install:
  - sudo apt update
  - sudo apt install -y freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev
  - pip install -e .
  - pip install coveralls
  - pip install jupyter

script:
  - nose2 --with-coverage

after_success:
  - coveralls
