# A sample code to test the python OpenDSS interface
from utils.openDSS.DSSStartup import DSSStartup
from utils.openDSS.setInfo import *
from utils.openDSS.getInfo import *
import numpy as np
import matplotlib.pyplot as plt


# DSSStartup returns a dictionary
result= DSSStartup()
dssText=result['dsstext']
dssSolution=result['dsssolution']
dssCircuit=result['dsscircuit']
DSSObj=result['dssobj']
# Compile the circuit
dssText.Command="Compile C:/feeders/feeder13_U_R_Pecan/feeder13_U_R_Pecan.dss"


setRegInfo(DSSObj,['lvr-lvr_01'],'maxtapchange',[16],0)
setCapInfo(DSSObj,['cap_675'],'kvar',[600],0)


setSolutionParams(DSSObj,'daily',1440,1,'time',1000,100)

# Run a Power Flow Solution
dssSolution.Solve()


regInfo=getRegInfo(DSSObj,[])
MaxTap=[d['maxtapchange'] for d in regInfo]
print('Max Taps for Regulators:'+ str(MaxTap))

capInfo=getCapInfo(DSSObj,[])
KVAR=[d['kvar'] for d in capInfo]
print('Cap KVAR info:'+ str(KVAR))

setCapControlInfo(DSSObj,['capc_611','capc_675'],'offsetting',[1.01,1.01])

DSSMon=dssCircuit.Monitors
#  Set this one as the active monitor
DSSMon.Name='VAR_Meter_675'
#  print the monitor name
print('Monitor Name:' + str(DSSMon.name))

Headers=DSSMon.Header
# print('Header Name' + str(Headers))
time=3600*np.asarray((DSSMon.dblHour))
Reactive_power=np.asarray(DSSMon.Channel(2))+np.asarray(DSSMon.Channel(4))+np.asarray(DSSMon.Channel(6))

plt.figure()
plt.plot(time,-Reactive_power)
plt.title('VAR generated by Capacitor')
plt.show()


DSSMon.Name='meter_675'
print('Monitor Name:' + str(DSSMon.name))
Voltage=np.asarray(DSSMon.Channel(1))

plt.figure()
plt.plot(time,Voltage/2400) #2400 is the base voltage
plt.title('Voltage recorded at meter 675')
plt.show()


